### ISSUE TITLE
valore strano range

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sergioconsoli/prisma-data-portal#3]
```
I dataset e ontologia sono tutti caricati sul nostro Virtuoso in Wit, e 
accessibili tramite content negotiation:
http://www.ontologydesignpatterns.org/ont/prisma/indirizzo

il valore del range per questa proprietà è stranissimo, Io visualizzo: 
-6a507b0:14acfcdf27e:-7fed

ma cosa vuol dire “bitumatura indirizzo”? E’ uno dei valori di 
rdfs:label…


```

Original issue reported on code.google.com by `consoli....@gmail.com` on 22 Jan 2015 at 3:59

**Comment by sergioconsoli** [comment]
SELECT * 
FROM<prisma-ont>
WHERE{
    <http://www.ontologydesignpatterns.org/ont/prisma/indirizzo> ?p ?v
}

**Comment by sergioconsoli** [comment]
SELECT * 
FROM<prisma>
WHERE{
    ?s ?p ?o .
FILTER(CONTAINS(STR(?o), "bitumatura Indirizzo"))
}

**Comment by sergioconsoli** [comment]
quel valore strano nel range di prisma:indirzzo è un blank node nell'ontologia, è una classe definita on-the-fly per restrizione.
Se si va sull'ontologia
http://www.ontologydesignpatterns.org/ont/prisma/ontology.owl
e si va su: 
http://www.ontologydesignpatterns.org/ont/prisma/indirizzo
il range è una collection:
<owl:Class>
<owl:unionOf rdf:parseType="Collection">
<rdf:Description rdf:about="http://www.ontologydesignpatterns.org/ont/prisma/NumeroCivico"/>
<rdf:Description rdf:about="http://www.ontologydesignpatterns.org/ont/prisma/Via"/>
</owl:unionOf>
</owl:Class>
per questo spunta il blank node nel range, ci deve essere per forza.
