### ISSUE TITLE
alcuni civici assenti

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sergioconsoli/prisma-data-portal#4]
```
http://www.ontologydesignpatterns.org/data/prisma/chiesa/chiesa-basilica-cattedr
ale
se clicco su 
http://www.ontologydesignpatterns.org/data/prisma/numerocivico/v-v-emanuele-163 
non c’è niente. 



```

Original issue reported on code.google.com by `consoli....@gmail.com` on 22 Jan 2015 at 4:00

**Comment by sergioconsoli** [comment]
Erano dei civici che erano stati creati dinamicamente durante i link ad altre entità, e che non erano ancora esistenti in NumeriCivici erroneamente. Adesso sono stati tutti editati, e non ce ne sono piu' di vuoti

**Comment by sergioconsoli** [comment]
Per memo mia:

select addresses vuoti:

SELECT DISTINCT ?o
FROM<prisma>
WHERE{
    ?s <http://www.ontologydesignpatterns.org/ont/prisma/indirizzo> ?o .
    FILTER(STRSTARTS(STR(?o), "http:")) .
    FILTER NOT EXISTS { ?o ?p ?v }
}

--------------

select max indice:

SELECT DISTINCT MAX(?i) as ?m
FROM<prisma>
WHERE{
    ?s a	<http://www.ontologydesignpatterns.org/ont/prisma/NumeroCivico> .
?s <http://www.ontologydesignpatterns.org/ont/prisma/identificativo> ?i .
}
