### ISSUE TITLE
inconcine lodview e lodlive in inglese

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sergioconsoli/prisma-data-portal#5]
```
Se vedi nella pagina delle content ci sono due inconcine che linkano 
l’oggetto sia a LodView che a LodLive, 

, possiamo scriverlo anche in inglese? (visualize with LodView…)


```

Original issue reported on code.google.com by `consoli....@gmail.com` on 22 Jan 2015 at 4:00

**Comment by sergioconsoli** [comment]
Purtroppo non si puo' fare nella doppia lingua, la pagina è costruita dinamicamente con felix e per fare la doppia lingua ci sarebbe un gran da fare, ed il tutto per cambiare solo una nomenclatura.
Inoltre il tutto (ontologia e dati) sono targati per l'Italiano, quindi non ha molto senso mettere le diciture anche in Inglese.
