### ISSUE TITLE
URI con namespace per Catania

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sergioconsoli/prisma-data-portal#6]
```
1) costruire le URI con un namespace che al Comune di Catania vada bene, ex. 
http://www.comune.catania.it/dati/…


```

Original issue reported on code.google.com by `consoli....@gmail.com` on 22 Jan 2015 at 4:03

**Comment by sergioconsoli** [comment]
questo sarà fatto al momento dell'istallazione sul server del partenariato
