### ISSUE TITLE
licenza dati dal comune

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sergioconsoli/prisma-data-portal#7]
```
pubblichiamo le applicazioni, ma senza permettere lo scaricamento dei dataset 
se/finché il Comune non stabilisce la licenza


```

Original issue reported on code.google.com by `consoli....@gmail.com` on 22 Jan 2015 at 4:03

**Comment by sergioconsoli** [comment]
questo sarà discusso al momento dell'istallazione sul server del partenariato
